### ISSUE TITLE
Site text not rendering right on mobile

### ISSUE THREAD

**Issue by nsunami** [eur-nl/data-coffee-breaks#1]
I was looking at the site on my mobile, and it cuts off the text horizontally.

![eur-nl github io_data-coffee-breaks_(iPhone XR)](https://user-images.githubusercontent.com/17035406/221518194-0eb98c7b-477e-4f75-bab3-81bf2e8b6111.png)

I think it's because the wrapper and section widths are fixed on pixels (`style.scss`).

**Comment by eduardklap** [comment]
Oh thanks for notifying! I will look for a solution
I fixed a width to make it more readable, so I will try to find a solution that retains that while the issue on the mobile is fixed

**Comment by eduardklap** [comment]
Mobile view improved (although still not perfect) on my phone at least by adding a media query: [see this commit](https://github.com/eur-nl/data-coffee-breaks/commit/fa43fd4a3ab7605cffbb371200eb377873de24a6)
I will close this issue for now, feel free to reopen if it has not improved for you
